project:
  type: website
  output-dir: docs

website:
  title: "Albert's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Albert0011
format:
  html:
    theme: cosmo
    css: styles.css



